; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno
src_dir = ardufocus

[common]
lib_ignore = 
build_flags = -Wall -Wextra -fno-exceptions -fmax-errors=1
src_build_flags = 
lib_deps_external = 

[env:uno]
platform = atmelavr
board = uno
lib_ignore = ${common.lib_ignore}
build_flags = ${common.build_flags}
src_build_flags = ${common.src_build_flags}
lib_deps = ${common.lib_deps_external}
